baseURL = "https://example.com/"
languageCode = "en-us"
title = "Eddie Webb"
theme = "hugo-resume"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    firstName = "Daniel"
    lastName = "Wing"
    address = "Mexico City"
    phone = "+52.55.31.34.32.38"
    contactNote = "Opereations & Development Manager"
    profileImage = "img/dw.jpg"
    email = "daniel.wing@gmail.com"
    description = " Over 10 years tenure managing different size teams starting with ten delivery experts to ten directors and two coordinators on a 300-people operation for a national public institution. An expert mixing cold data-driven decisions with warm soft-skills to lead operations with special attention to the Customer Experience. Training specialist with a creative and artistry approach to a constructivist learning experience. Excellent oral and written communication skills, strong analytical skills and critical thinking. Proactive with a problem-solving mindset that includes both the strategic and operative approach."
    favicon = "images/favicon.ico"
    # what sections
    showExperience = true
    showSkills = true
    showProjects = true
    showEducation = true
    showOpenSource = true
    showPublications = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/daniel-wing/"


[[params.handles]]
    name = "GitHub"
    link = "https://github.com/daniel-wing/"

[[params.handles]]
    name = "Bitbucket"
    link = "https://bitbucket.org/danielwing/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/5890190/daniel-wing"
    icon = "stack-overflow"

[[params.handles]]
    name = "Keybase"
    link = "https://keybase.io/danielwing"
    icon = "key"

[params.google.analytics]
    trackerID = "#XX-123446-01"
